version: '3'
services:
  mysql:
    build:
      dockerfile: ./bd.dockerfile
      context: .
    image: capsrnrb/mysql
    container_name: mysql
    ports: 
      - 3306:3306
    networks: 
      - capsrnrb-network

networks:
  capsrnrb-network:
    driver: bridge
