version: '3'
services:
  mysql:
    build:
      dockerfile: ./bd.dockerfile
      context: .
    image: capsrnrb/mysql
    container_name: mysql
    ports: 
      - 3306:3306
    networks: 
      - capsrnrb-network

  tomcat:
    build: 
      dockerfile: ./tomcat.dockerfile
      context: .
    image: capsrnrb/tomcat
    container_name: tomcat8
    ports: 
      - 8080:8080
    networks: 
      - capsrnrb-network
    depends_on: 
      - mysql  

networks:
  capsrnrb-network:
    driver: bridge
